### ISSUE TITLE
Error in parser

### ISSUE THREAD

**Issue by 1Map** [jamesp/node-nmea#21]
```
Error: Error in parsing:$PORZD,A,017.9*33
    at Error (native)
    at Object.exports.parse (/home/pi/nodeapp/node_modules/nmea/nmea.js:78:13)
    at SerialPort.<anonymous> (/home/pi/nodeapp/index.js:16:20)
    at emitOne (events.js:96:13)
    at SerialPort.emit (events.js:188:7)
    at /home/pi/nodeapp/node_modules/serialport/lib/parsers.js:24:17
    at Array.forEach (native)
    at SerialPort.<anonymous> (/home/pi/nodeapp/node_modules/serialport/lib/parsers.js:23:13)
    at SerialPort._emitData (/home/pi/nodeapp/node_modules/serialport/lib/serialport.js:313:18)
    at SerialPort.<anonymous> (/home/pi/nodeapp/node_modules/serialport/lib/serialport.js:293:14)
```

From `cat /dev/ttyAMA0` I get:

```
$GPGGA,....
$GPRMC,....
$GPGSV,....
$GPGSV,....
$GPGSV,....
$GPGSV,....
$GLGSV,....
$GLGSV,....
$GNGSA,....
$GNGSA,....
$PORZD,A,040.3*3B
```

I do not think you handle the last line: `PORZD - RMS Error of Coordinates`

The PORZD message contains coordinates validity data and estimation of plane coordinates RMS (root mean square) value.

See the Propriety Messages under:
http://nvs-gnss.com/support/documentation/item/download/51.html

**Comment by jamesp** [comment]
Hi @1Map.  I don't think anyone has yet implemented a codec to decode that sentence.  You can create one using one of the existing files as a template - add it to the `codecs` folder and `nmea.js`, or simply add support in your application by adding a decode function to `traditionalDecoders["PORZD"]`.
